root: true

env:
  node: true
  jest: true

extends: [airbnb, plugin:flowtype/recommended]

plugins:
  - react
  - jsx-a11y
  - import
  - flowtype

rules:
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  max-len: [1, {"code": 120}]
  import/no-extraneous-dependencies: ["error", {"devDependencies": true, "optionalDependencies": false, "peerDependencies": false}]
  no-console: [0] #temp
  no-underscore-dangle: ["error", { "allow": ["_id"] }]
  linebreak-style: [0, "unix"]

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true

globals:
  window: true
  componentHandler: true
  document: true
  location: true
