root: true

env:
  node: true

extends: airbnb

plugins:
  - react
  - jsx-a11y
  - import

rules:
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]

globals:
  window: true
  componentHandler: true
