language: node_js

node_js:
  - '6.1'
  - '6'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - npm run flow:build

script:
  - npm run lint
  - npm run flow
  - npm run test
